### ISSUE TITLE
Is this repository still actively being developed, or do you recommend HoloToolkit-Unity for HoloLens development?

### ISSUE THREAD

**Issue by Tam66662** [microsoft/MixedRealityToolkit#108]
As the title suggests, I was curious as to how this repository is different from the HoloToolkit-Unity repo...is this one a subset?  And is one recommended over the other for current HoloLens development?

Thanks,
Tam

**Comment by StephenHodgson** [comment]
The HoloToolkit-Unity repo uses this HoloToolkit repo as a base.
