### ISSUE TITLE
MicStreamSelector.dll fails to pass WACK

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit#116]
See https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/987

**Comment by keveleigh** [comment]
Do you have any additional info? I'm unable to repro this.

**Comment by StephenHodgson** [comment]
It'll pass WACK locally, but when you submit it to the store it'll fail.

**Comment by keveleigh** [comment]
Is there any failure message?

**Comment by keveleigh** [comment]
ping. It's not great to have this missing from the Toolkit and have it been pulled out without any repro or additional info...

**Comment by StephenHodgson** [comment]
Sorry, I never got a reply from my dev.  Still waiting on a reply here too.

**Comment by StephenHodgson** [comment]
I got a reply, but the log wasn't specific about MicStreamSelector.  Just the SpatialUnderstanding, and Planefinding.dlls.

**Comment by keveleigh** [comment]
So MicStreamSelector should be re-added?

**Comment by StephenHodgson** [comment]
See #123

**Comment by keveleigh** [comment]
Is that what's causing WACK to fail? Doesn't sound like it would in apps that don't use the recording features of the DLL (and, in that case, the app shouldn't be shipping without that capability anyway).
