### ISSUE TITLE
Fast Configurable 2 Sided shader only supports Texture when it's set at the start

### ISSUE THREAD

**Issue by LocalJoost** [Microsoft/MixedRealityToolkit#123]
If you use the Fast Configurable 2 Sided shader , don't set an initial Texture and try to set it runtime it will not display the texture
Workaround - set a dummy texture at startup . Any texture. Just make sure there is a startup texture.

**Comment by StephenHodgson** [comment]
@LocalJoost, I think you may have wanted to open this issue on the Unity specific repo.

**Comment by LocalJoost** [comment]
I didn't? Whoops


Joost van Schaik

Windows Development MVP

"The world as I envision it in my head is such a more interesting place"

________________________________

**Comment by LocalJoost** [comment]
Sorry. Wrong place to place this
