### ISSUE TITLE
Single air tap registers as double air tap with OnInputClicked (); 

### ISSUE THREAD

**Issue by mr-mystery** [Microsoft/MixedRealityToolkit#126]
Hi @StephenHodgson,

I've been creating a functionality for my project. And the functionality is that when the object (Box) collides (using OnTriggerEnter()) with another object (Cylinder) with rigidbody and certain component in the Box object should get disabled. This functionality is working fine. But a script in the Box object which has the OnInputClicked () method registers every tap as a double tap which makes a bool as true and false at the same time which messes up my work. Does anyone have this issue?

P.S. The OnInputClicked () function worked normally before the collision.
Unity Version: 2017.1.2f1.
HoloToolkit Version: v1.2017.2.0.

**Comment by StephenHodgson** [comment]
Please open a new issue on the [MRTK for unity repository](https://github.com/Microsoft/MixedRealityToolkit-Unity)
