### ISSUE TITLE
Visual Studio 2017 will not build RoomDemo.  Compiler error C1001

### ISSUE THREAD

**Issue by Craniac** [Microsoft/MixedRealityToolkit#143]
I've just updated to Windows 10 Pro and Studio 2017.  As I work through the sample code for this project, SpatialInput\DemoRoom does not compile.  I encounter 8 errors, all seemingly related to compiling template code with automatic variables, always within a "for" loop.

As far as I can tell I'm compiling with default settings for target platform = "x64".
Target Windows version is 10.0.16299.0.

Same problem for Debug and Release builds, and I'ce confirmed that optimization is turned off for the Debug build.

I can start slogging through trying to unwind the "for" loops, but there's certainly someone who can do it far faster and with higher certainty than I.

Perhaps there's just a compiler setting that needs to be tweaked?

Compile error msgs and system information below...

----------------------------
Here's the error output:

1>------ Build started: Project: Neso, Configuration: Debug x64 ------
1>EasingSystem.cpp
1>HolographicRenderer.cpp
1>PbrModelCache.cpp
1>PhysicsSystem.cpp
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\engine\easingsystem.cpp(23): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp', line 8163)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\engine\easingsystem.cpp(14): note: see reference to function template instantiation 'std::vector<std::tuple<Neso::Transform *,Neso::Easing *>,std::allocator<_Ty>> Neso::EntityStore::GetComponents<Neso::Transform,Neso::Easing>(void)' being compiled
1>        with
1>        [
1>            _Ty=std::tuple<Neso::Transform *,Neso::Easing *>
1>        ]
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\engine\physicssystem.cpp(35): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp', line 8163)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\engine\physicssystem.cpp(16): note: see reference to function template instantiation 'std::vector<std::tuple<Neso::Transform *,Neso::RigidBody *>,std::allocator<_Ty>> Neso::EntityStore::GetComponents<Neso::Transform,Neso::RigidBody>(void)' being compiled
1>        with
1>        [
1>            _Ty=std::tuple<Neso::Transform *,Neso::RigidBody *>
1>        ]
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\engine\pbrmodelcache.cpp(105): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp', line 8163)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\engine\pbrmodelcache.cpp(58): note: see reference to function template instantiation 'std::vector<std::tuple<Neso::PbrRenderable *>,std::allocator<_Ty>> Neso::EntityStore::GetComponents<Neso::PbrRenderable>(void)' being compiled
1>        with
1>        [
1>            _Ty=std::tuple<Neso::PbrRenderable *>
1>        ]
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\engine\holographicrenderer.cpp(337): fatal error C1001: An internal error has occurred in the compiler.
1>(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp', line 8163)
1> To work around this problem, try simplifying or changing the program near the locations listed above.
1>Please choose the Technical Support command on the Visual C++
1> Help menu, or open the Technical Support help file for more information
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\engine\holographicrenderer.cpp(196): note: see reference to function template instantiation 'std::vector<std::tuple<Neso::Transform *,Neso::PbrRenderable *>,std::allocator<_Ty>> Neso::EntityStore::GetComponents<Neso::Transform,Neso::PbrRenderable>(void)' being compiled
1>        with
1>        [
1>            _Ty=std::tuple<Neso::Transform *,Neso::PbrRenderable *>
1>        ]
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\engine\holographicrenderer.cpp(125): note: see reference to class template instantiation 'winrt::impl::fast_iterator<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::Graphics::Holographic::HolographicCameraPose>>' being compiled
1>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\libs\neso\common\directxhelper.h(16): note: see reference to class template instantiation 'winrt::impl::await_adapter<winrt::Windows::Foundation::IAsyncOperation<winrt::Windows::Storage::Streams::IBuffer>>' being compiled (compiling source file Engine\HolographicRenderer.cpp)
1>Done building project "Neso.vcxproj" -- FAILED.
2>------ Build started: Project: DemoRoom, Configuration: Debug x64 ------
2>DemoRoomMain.cpp
2>ToolboxSystem.cpp
2>PaintStrokeSystem.cpp
2>MotionControllerSystem.cpp
2>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\samples\demoroom\paintstrokesystem.cpp(147): fatal error C1001: An internal error has occurred in the compiler.
2>(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp', line 8163)
2> To work around this problem, try simplifying or changing the program near the locations listed above.
2>Please choose the Technical Support command on the Visual C++
2> Help menu, or open the Technical Support help file for more information
2>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\samples\demoroom\paintstrokesystem.cpp(26): note: see reference to function template instantiation 'std::vector<std::tuple<DemoRoom::PaintStrokeComponent *,Neso::PbrRenderable *>,std::allocator<_Ty>> Neso::EntityStore::GetComponents<DemoRoom::PaintStrokeComponent,Neso::PbrRenderable>(void)' being compiled
2>        with
2>        [
2>            _Ty=std::tuple<DemoRoom::PaintStrokeComponent *,Neso::PbrRenderable *>
2>        ]
2>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\samples\demoroom\toolboxsystem.cpp(281): fatal error C1001: An internal error has occurred in the compiler.
2>(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp', line 8163)
2> To work around this problem, try simplifying or changing the program near the locations listed above.
2>Please choose the Technical Support command on the Visual C++
2> Help menu, or open the Technical Support help file for more information
2>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\samples\demoroom\toolboxsystem.cpp(145): note: see reference to function template instantiation 'std::vector<std::tuple<Neso::Transform *,DemoRoom::ToolSelectorKey *>,std::allocator<_Ty>> Neso::EntityStore::GetComponents<Neso::Transform,DemoRoom::ToolSelectorKey>(void)' being compiled
2>        with
2>        [
2>            _Ty=std::tuple<Neso::Transform *,DemoRoom::ToolSelectorKey *>
2>        ]
2>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\samples\demoroom\motioncontrollersystem.cpp(181): fatal error C1001: An internal error has occurred in the compiler.
2>(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp', line 8163)
2> To work around this problem, try simplifying or changing the program near the locations listed above.
2>Please choose the Technical Support command on the Visual C++
2> Help menu, or open the Technical Support help file for more information
2>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\samples\demoroom\motioncontrollersystem.cpp(78): note: see reference to function template instantiation 'std::vector<std::tuple<Neso::Transform *,DemoRoom::MotionControllerComponent *>,std::allocator<_Ty>> Neso::EntityStore::GetComponents<Neso::Transform,DemoRoom::MotionControllerComponent>(void)' being compiled
2>        with
2>        [
2>            _Ty=std::tuple<Neso::Transform *,DemoRoom::MotionControllerComponent *>
2>        ]
2>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\samples\demoroom\motioncontrollersystem.cpp(77): note: see reference to class template instantiation 'winrt::impl::fast_iterator<winrt::Windows::Foundation::Collections::IVectorView<winrt::Windows::UI::Input::Spatial::SpatialInteractionSourceState>>' being compiled
2>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\samples\demoroom\demoroommain.cpp(222): fatal error C1001: An internal error has occurred in the compiler.
2>(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp', line 8163)
2> To work around this problem, try simplifying or changing the program near the locations listed above.
2>Please choose the Technical Support command on the Visual C++
2> Help menu, or open the Technical Support help file for more information
2>d:\sandbox\windowsmixedreality\mixedrealitytoolkit-master\spatialinput\samples\demoroom\applogicsystem.h(22): note: see reference to function template instantiation 'std::vector<std::tuple<Neso::Entity *,Neso::Transform *>,std::allocator<_Ty>> Neso::EntityStore::GetComponentsWithEntity<Neso::Transform>(void)' being compiled
2>        with
2>        [
2>            _Ty=std::tuple<Neso::Entity *,Neso::Transform *>
2>        ] (compiling source file DemoRoomMain.cpp)
2>Done building project "DemoRoom.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 3 up-to-date, 0 skipped ==========

----------------------------
Here's my compiler lib version info, from Help/About...

Microsoft Visual Studio Professional 2017 
Version 15.5.5
VisualStudio.15.Release/15.5.5+27130.2026
Microsoft .NET Framework
Version 4.7.02556

Installed Version: Professional

Visual Basic 2017   00369-60000-00001-AA006
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA006
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA006
Microsoft Visual C++ 2017

Visual F# 4.1   00369-60000-00001-AA006
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.10.01106.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.31127.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Web Frameworks and Tools 2017   5.2.51007.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.31106.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.51120.3

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.4.11025.7
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61710.120
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   15.5.11025.1
TypeScript Tools for Microsoft Visual Studio

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Unity   3.5.0.3
Visual Studio Tools for Unity

Visual Studio Tools for Universal Windows Apps   15.0.27130.2020
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

-------------------------------

**Comment by ms-yl** [comment]
@Craniac  Please pull the latest master.  A workaround has been merged in recently that won't hit this compiler error anymore.   Let is know if you still see this.

**Comment by Craniac** [comment]
That seems to have fixed it.  I can compile and am moving onward.  Thanks!
