### ISSUE TITLE
SpeechInputSource is not able to differentiate certain strings.

### ISSUE THREAD

**Issue by Mikeman3561** [Microsoft/MixedRealityToolkit#144]
Before deploying an application to production we found that our application was not able to detect when the user said "112".

Input: "One One Two"
Output: Yields no results.

Input: "One One Two"
Output: Shows results for 113.

Input: "One Twelve"
Output: Shows results for 122.

**Comment by StephenHodgson** [comment]
This data comes from the Windows Speech APIs
