### ISSUE TITLE
Spatial Interaction Controller not available on RS4 - TapToPlace scene

### ISSUE THREAD

**Issue by ooeygui** [Microsoft/MixedRealityToolkit#155]
Repro steps:
  1) Install Insider build of RS4 on a HoloLens, enable developer mode, pair to VS.
  1) Create a new unity project, and import the MRTK & examples
  1) Add the TapToPlace sample scene
  1) Ensure appropriate capabilities are set
  1) Build and deploy to the HoloLens

Observe:
Failed to get spatial interaction controller - touchpad, thumbstick, and vendor data will be unavailable to the application for InteractionController! Error code: '0x00000000'.

Unable to tap to move the cubes around the scene.

**Comment by davidkline-ms** [comment]
Closing as this was re-recreated in the MixedRealityToolkit-Unity.  https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1992
