### ISSUE TITLE
DemoRoom can not work on Hololens Emulator

### ISSUE THREAD

**Issue by IngoChou** [Microsoft/MixedRealityToolkit#157]
Hello,

DemoRoom can not work on Hololens Emulator (14393).  
How can I run it on Hololens?

Thanks for your help.

**Comment by ms-yl** [comment]
@IngoChou   DemoRoom was designed to work in MixedReality headsets on Desktop Windows.  It's mostly to demo the motion controller capabilities.   It was not designed to work with Hololens, and UX shouldn't work very well without a motion controller.

However, the app itself should be running ok on hololens, although you cannot do much using hand input. Please let us know what specific error did you find and how can we help.

**Comment by IngoChou** [comment]
@ms-yl Thank you very much.

I want to develop app based on MixedRealityToolkit. And want to run my app not only on MixedReality headsets on desktop but also on hololens. 

I just found the demo "DemoRoom". It works on Mixed Reality portal, but crashes when works on Hololens Emulator (14393) with x86 version.  The error is a error HRESULT value "REGDB_E_CLASSNOTREG class not registered" has been checked by API check_hresult() located at line 5688 on file "base.h".

![crash](https://user-images.githubusercontent.com/30195882/40091640-7d3f4e1c-58eb-11e8-8c6a-f0323051e68e.PNG)

Thanks a lot.

**Comment by ms-yl** [comment]
I see.  The demo room requires a higher SDK version for new APIs such as StageFrameOfReference.  It is not available on windows 14393.   Hence the error.  

You probably retargeted the project from 16799 in order to deploy on Hololens emulator.  This demo room code cannot run before that version of windows.  

Best for you to wait for new Hololens release with new API support.

**Comment by IngoChou** [comment]
OK, I got it. Thank you for your reply and help.

**Comment by IngoChou** [comment]
Hello, @ms-yl 

It is still not work when I use Hololens Emulaor  10.0.17134.80


![mrcrash](https://user-images.githubusercontent.com/30195882/41903509-ba2f3df8-7968-11e8-94b1-33a64760892a.png)

Thanks.
