### ISSUE TITLE
PlaneFinding.DLL Source Code 

### ISSUE THREAD

**Issue by adrianimajion** [Microsoft/MixedRealityToolkit#158]
Hello,

Many thanks for all the great open source code in this project. I was wondering if the source for PlaneFinding.DLL is available, or if it could be released under the same license.

Best,
Adrian

**Comment by keveleigh** [comment]
Hello!

The PlaneFinding DLL source is indeed available in this repo, found here: https://github.com/Microsoft/MixedRealityToolkit/tree/master/SpatialMapping/PlaneFinding

**Comment by adrianimajion** [comment]
Thanks @keveleigh , don't know how I missed that.
