### ISSUE TITLE
Unable to find an entry point named 'CheckLibraryHasLoaded' in DLL 'SpectatorViewPlugin'

### ISSUE THREAD

**Issue by bdunajczyk** [Microsoft/MixedRealityToolkit#164]
Hello everyone. Recently I tried to compile **SpectatorView** example which comes with **MixedRealityToolkit** unfortunately without success. I did all of the steps introduced at: 
https://github.com/Microsoft/MixedRealityToolkit/tree/master/SpectatorViewPlugin
After adding above plugin to the **SpectatorView** project, another issues popped up, which I solved looking at:
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1867
At last application compiled and got deployed on HoloLens but after launching I got this error:

```
System.EntryPointNotFoundException: Unable to find an entry point named 'CheckLibraryHasLoaded' in DLL 'SpectatorViewPlugin'.
   at HoloToolkit.Unity.SpectatorView.OpenCVUtils.CheckOpenCVWrapperHasLoaded()
   at HoloToolkit.Unity.SpectatorView.SpectatorViewNetworkDiscovery.Awake()
```

And I'm stuck. Does anyone know how to solve this problem? Unity sees **SpectatorViewPlugin.dll** as _native_ dll instead of _managed_ but I don't know if it has something to do with the error.
Thanks, regards,
Błażej

**Comment by keveleigh** [comment]
This sounds like an issue that was inadvertently introduced last week, but should have been fixed in Microsoft/MixedRealityToolkit-Unity#2168, which made its way into the most recent RC release. If you try the lastest May branch or the latest RC release, do you still see the issue?

**Comment by bdunajczyk** [comment]
Hi @keveleigh, unfortunately **2017.4.0.0 Release Candidate 2** is lacking of **SpectatorView** directory. When I open **SpectatorViewExample.scene** from new examples package there are Missing Prefabs
![image](https://user-images.githubusercontent.com/1785619/40642338-1e57832e-631d-11e8-8671-75df315b4312.png)

**Comment by keveleigh** [comment]
That's correct. The SpectatorView feature has been moved to the preview package until it's able to pass WACK. Looks like we forgot to move the examples properly though! Per the release notes:

> Import HoloToolkit-Unity-PreviewFeatures-2017.4.0.0-rc2.unitypackage to include SpectatorView in your project.

**Comment by bdunajczyk** [comment]
Thank you @keveleigh, everything seems to work smoothly now! High five!

**Comment by ww362184099** [comment]
In the Unity2018.3.14,OpenCVUtils.CheckOpenCVWrapperHasLoaded() doesn't work success,and throwing an exception,but it works well in Unity2017.4.5.Could you please tell me the reason? @keveleigh
