### ISSUE TITLE
SpectatorView plugin prompts to move dll files to unexisting folder

### ISSUE THREAD

**Issue by danielescudero** [microsoft/MixedRealityToolkit#168]
"Add the DLLs to your Project
Copy the following dlls from the directory MixedRealityToolkit\SpectatorViewPlugin\SpectatorViewPlugin\Release\SpectatorViewPlugin to the directory HoloToolkit\SpectatorView\Plugins\WSA\x86\" ...when HoloToolkit\SpectatorView\Plugins\WSA\x86\ does not exist. Now that SPecView has it's own folder it adds to more confusion.

**Comment by aanexplus** [comment]
I have the same issue. Where do I copy those dlls to? Do I have to create the directory in my game HoloToolkit asset?

**Comment by CommanderLee** [comment]
We can create the directory by ourselves. I noticed that they fixed the instruction, and now the instruction says we should create the directory.

**Comment by chrisfromwork** [comment]
I'm going to close this issue based on a lack of activitity. @danielescudero please reopen this issue if it's needed.
