### ISSUE TITLE
X

### ISSUE THREAD

**Issue by IngoChou** [Microsoft/MixedRealityToolkit#173]

**Comment by ms-yl** [comment]
The code base hasn't been changed for a while.  We cannot reproduce this issue on our side.   Is this a unique problem for this project or happens in other projects as well?

**Comment by IngoChou** [comment]
I tested today. This problem also happens in an other project: ControllerRenderSample.

**Comment by StephenHodgson** [comment]
@IngoChou why are you removing title and content from your issues?
