### ISSUE TITLE
SpectatorViewPlugin: Camera and Distortion Matrix

### ISSUE THREAD

**Issue by verenuschka** [microsoft/MixedRealityToolkit#174]
Hi there,

I've been using the SpectatorViewPlugin dlls for the SpectatorView (Preview) project in the MixedRealityToolkit-Unity (https://docs.microsoft.com/en-us/windows/mixed-reality/spectator-view). 
Other than just tracking the marker with the HoloLens, I tried displaying a virtual object on top of it but got very inaccurate results (the virtual object is shifted by a few cm and the rotation is a bit off).

I noticed that the camera and distortion matrix are hard-coded inside the MarkerDetector.cpp in this project and thought this might cause the inaccuracies. 
So I wanted to ask if that could even be the case as I thought HoloLenses are all calibrated the same.
As an additional info: the processed images have a resolution of 896x504. Could the matrices maybe be calculated using a different resolution, causing this problems?

Thanks in advance!

**Comment by chrisfromwork** [comment]
There are definitely some issues with the marker detection logic used in holotoolkit's spectator view preview:
1) Camera intrinsic and distortion matrices vary between devices. These hard-coded values were a quick hack by the original contributors to get things working, but they can definitely be a point of inaccuracy.
2) The math for determining the orientation and position of the detected marker is incorrect. We've made some improvements in a refactor of spectator view underway to fix these inaccuracies. If you would like to see examples of what was done differently, take a look at the following code:

New mechanism for obtaining camera intrinsics/extrinsics/distortion:
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/41e3feaddb26c1d20c3a6571b7d3500604a314a6/Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/MarkerDetection/ArUco/HoloLens/SpectatorViewPluginArUcoMarkerDetector.cs#L139

New math based on opencv marker detection:
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/41e3feaddb26c1d20c3a6571b7d3500604a314a6/Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/MarkerDetection/ArUco/HoloLens/SpectatorViewPluginAPI.cs#L130

New plugin using updated camera information:
https://github.com/Microsoft/MixedRealityToolkit/blob/76873bec5a0997bb97f285d7b0f94e0ea1b0c0e6/SpectatorViewPlugin/SpectatorViewPlugin/SpectatorViewPlugin/MarkerDetector.cpp#L39

**Comment by chrisfromwork** [comment]
I'm going to close this issue based on a lack of activitity. The correct intrinsics should be obtained from the HoloLens in our new spectator view refactor. @verenuschka please reopen this issue if it's still needed.
