### ISSUE TITLE
SpectatorViewPlugin Build Error

### ISSUE THREAD

**Issue by Vernimator** [microsoft/MixedRealityToolkit#182]
I have been following the instructions to build the Spectator View Plugin and when trying to build the plugin I get the following.

1>------ Build started: Project: SpectatorViewPlugin, Configuration: Release Win32 ------
1>Object reference not set to an instance of an object.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Vcpkg install seemed to install without issue.. I tried reinstalling Vcpkg and it returned that "Package opencv:x86-uwp is already installed". Am I missing something?

Please advise.

Thx

**Comment by tvald** [comment]
Reported on the Unity WMR forum: https://forum.unity.com/threads/system-notimplementedexception-when-a-photocaptureframe-instantiated.576460/

**Comment by CommanderLee** [comment]
I tried today and got the same output: Object reference not set to an instance of an object.

Vckpg installation seems to be successful. I don't know why.

**Comment by CommanderLee** [comment]
@Vernimator  I found an extension and it solved this problem for me. Refer: https://stackoverflow.com/questions/34084003/visual-studio-2015-error-object-reference-not-set-to-an-instance-of-an-object

**Comment by leo92613** [comment]
@Vernimator @CommanderLee 
I had the same issue and I fixed it
It's because the opencv lib link in the sln is outdated.it should be xx343.lib instead of xx341.lib
Simply goes to the sln property page under Linker/Input, you can change them manually and it will build .

I suggest @keveleigh @davidkline-ms @danielescudero update the sln file

**Comment by cindychen0204** [comment]
@CommanderLee @keveleigh @davidkline-ms  @danielescudero 

Hi there, I can not fix the error, either.

However, after I have changed the  Linker/Input to xx343.lib, more error appeared...

any advise?

Thanks.

It is in Japanese, but meaning: 
"unresolved external symbol XXX"

![](https://i.gyazo.com/462336489d14b91598955d5f3a506888.png)

**Comment by chrisfromwork** [comment]
Documentation has been updated to call out these potential lib issues.

If you experience this problem again in the future, please reopen this issue.
