### ISSUE TITLE
Build Error when installing OpenCV Contrib for UWP

### ISSUE THREAD

**Issue by ChauNTran** [Microsoft/MixedRealityToolkit#185]
Hi,
I'm following the steps to build the Spectator view plugin and got this error while installing OpenCV Contrib for uwp.
What am I missing? I included the log down here.

Microsoft Windows [Version 10.0.17134.345]
(c) 2018 Microsoft Corporation. All rights reserved.

D:\BV projects\SpectatorView\vcpkg>.\vcpkg install opencv[contrib]:x86-uwp --recurse
The following packages will be built and installed:
  * eigen3[core]:x86-uwp
  * libjpeg-turbo[core]:x86-uwp
  * liblzma[core]:x86-uwp
  * libpng[core]:x86-uwp
    opencv[contrib,core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp
  * opengl[core]:x86-uwp
  * tiff[core]:x86-uwp
  * zlib[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/8: liblzma:x86-uwp
Building package liblzma[core]:x86-uwp...
A suitable version of cmake was not found (required v3.11.4). Downloading portable cmake v3.11.4...
Downloading cmake...
Downloading cmake... done.
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
Downloading 7zip... done.
Extracting 7zip...
A suitable version of nuget was not found (required v4.6.2). Downloading portable nuget v4.6.2...
Downloading nuget...
Downloading nuget... done.
Extracting 7zip... done.
Extracting cmake... done.
-- Downloading https://github.com/xz-mirror/xz/archive/v5.2.4.tar.gz...
-- Extracting source D:/BV projects/SpectatorView/vcpkg/downloads/xz-mirror-xz-v5.2.4.tar.gz
-- Using source at D:/BV projects/SpectatorView/vcpkg/buildtrees/liblzma/src/v5.2.4-0e2feaf554
-- Applying patch D:/BV projects/SpectatorView/vcpkg/ports/liblzma/enable-uwp-builds.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: D:/BV projects/SpectatorView/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: D:/BV projects/SpectatorView/vcpkg/buildtrees/liblzma/x86-uwp-dbg
    See logs for more information:
      D:\BV projects\SpectatorView\vcpkg\buildtrees\liblzma\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/liblzma/portfile.cmake:25 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package liblzma:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: liblzma:x86-uwp
  Vcpkg version: 2018.10.20-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by ChauNTran** [comment]
[install-x86-uwp-dbg-out.log](https://github.com/Microsoft/MixedRealityToolkit/files/2520232/install-x86-uwp-dbg-out.log)

**Comment by fieldsJacksonG** [comment]
+ @danielescudero

**Comment by ChauNTran** [comment]
Thanks for replying. Yes I installed vcpkg.

**Comment by danielescudero** [comment]
Thanks @ChauNTran I'm getting the exact same error. There seems to be an open issue with vcpkg: https://github.com/Microsoft/vcpkg/issues/4574

**Comment by ras0219-msft** [comment]
We're fixing this issue upstream in vcpkg; the branch `dev/roschuma/4574` has a fix and will be checked in to master once we have confirmed it doesn't regress other platforms.

Sorry for the trouble!

**Comment by ras0219-msft** [comment]
The fix is now checked in to vcpkg master.

**Comment by ChauNTran** [comment]
Thank you. It works now.
