### ISSUE TITLE
SpectatorView Plugin - Error Installing OpenCV Contrib for UWP

### ISSUE THREAD

**Issue by blo85** [microsoft/MixedRealityToolkit#190]
D:\Users\108092\Desktop\sV\vcpkg>.\vcpkg install opencv[contrib]:x86-uwp --recurse

The following packages will be built and installed:
  * eigen3[core]:x86-uwp
  * libjpeg-turbo[core]:x86-uwp
  * libpng[core]:x86-uwp
    opencv[contrib,core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp
  * opengl[core]:x86-uwp
  * tiff[core]:x86-uwp
  * zlib[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/7: eigen3:x86-uwp
Building package eigen3[core]:x86-uwp...
A suitable version of cmake was not found (required v3.11.4). Downloading portable cmake v3.11.4...
Downloading cmake...
  https://cmake.org/files/v3.11/cmake-3.11.4-win32-x86.zip -> D:\Users\108092\Desktop\sV\vcpkg\downloads\cmake-3.11.4-win32-x86.zip
Downloading cmake... done.
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> D:\Users\108092\Desktop\sV\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
File does not have the expected hash:
             url : [ https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 ]
       File path : [ D:\Users\108092\Desktop\sV\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg.part ]
   Expected hash : [ 8c75314102e68d2b2347d592f8e3eb05812e1ebb525decbac472231633753f1d4ca31c8e6881a36144a8da26b2571305b3ae3f4e2b85fc4a290aeda63d1a13b8 ]
     Actual hash : [ a9dfaaafd15d98a2ac83682867ec5766720acf6e99d40d1a00d480692752603bf3f3742623f0ea85647a92374df405f331afd6021c5cf36af43ee8db198129c0 ]

**Comment by keveleigh** [comment]
@ras0219-msft Is this a side effect of https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3169#issuecomment-440479084? It looks like that commit is a few days older.

**Comment by blo85** [comment]
Thank you both!

@ras0219-msft I have launched a "git merge master" and I have no longer received hash error, but
the compilation process has advanced to the point: package 4/7: tiff...., and i am receiving again the error @keveleigh was referencing. 

@BenWoodford summary: "Tiff doesn't build on the lastest master, which consequently means OpenCV fails. Not that it matters massively for this as it's the wrong version of OpenCV for the plugin anyway."....

The error:

Starting package 4/7: tiff:x86-uwp
Building package tiff[core]:x86-uwp...
-- Downloading http://download.osgeo.org/libtiff/tiff-4.0.10.tar.gz...
-- Extracting source D:/Users/108092/Desktop/sView/vcpkg/downloads/tiff-4.0.10.tar.gz
-- Applying patch add-component-options.patch
-- Applying patch fix-cxx-shared-libs.patch
-- Applying patch crt-secure-no-deprecate.patch
-- Using source at D:/Users/108092/Desktop/sView/vcpkg/buildtrees/tiff/src/4.0.10-208d032666
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at D:/Users/108092/Desktop/sView/vcpkg/scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: D:/Users/108092/Desktop/sView/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: D:/Users/108092/Desktop/sView/vcpkg/buildtrees/tiff/x86-uwp-dbg
    See logs for more information:
      D:\Users\108092\Desktop\sView\vcpkg\buildtrees\tiff\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  D:/Users/108092/Desktop/sView/vcpkg/scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  D:/Users/108092/Desktop/sView/vcpkg/ports/tiff/portfile.cmake:37 (vcpkg_install_cmake)
  D:/Users/108092/Desktop/sView/vcpkg/scripts/ports.cmake:71 (include)


Error: Building package tiff:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tiff:x86-uwp
  Vcpkg version: 2018.11.23-nohash

**Comment by chrisfromwork** [comment]
@blo85 are you still experiencing this issue? Has a more recent commit in vcpkg master been able to fix this problem?

**Comment by chrisfromwork** [comment]
I'm closing this issue based on a lack of activity. I believe vcpkg has fixed this problem.
