### ISSUE TITLE
SpectatorViewPlugin: Can't build sln:  opencv2\aruco.hpp is missing

### ISSUE THREAD

**Issue by DaRockJaeger** [microsoft/MixedRealityToolkit#191]
Hello,

I am following the steps in the ReadMe.md of the SpectatorView Plugin.
Everything works well, but when I want to build the sln,the opencv2 files are not found. Where can I get those files?

Best regards

**Comment by DaRockJaeger** [comment]
Hello, its me again.
When I want to install OpenCV Contrib for UWP using ".\vcpkg install opencv[contrib]:x86-uwp --recurse", it tells me that no suitable version of 7zip was found, and it wants to download portable version of 7zip.

Then I get error:
File does not has the expected hash.

so the problem is with installing the vcpkg, not with SpectatorViewPlugind   :D

**Comment by Emerson92** [comment]
I get the same error too.

**Comment by Emerson92** [comment]
solution:
https://github.com/Microsoft/vcpkg/issues/4663
![default](https://user-images.githubusercontent.com/13955075/49572626-24e1c380-f977-11e8-8f44-28b9d69a2acd.png)

**Comment by chrisfromwork** [comment]
@DaRockJaeger were you able to get past this issue?

**Comment by chrisfromwork** [comment]
I am closing this issue for now based on a lack of activity. Please reopen this issue in the future if the problem persists.
