### ISSUE TITLE
Unable to build SpectatorViewPlugin - cannot find opencv2\aruco.hpp

### ISSUE THREAD

**Issue by Emerson92** [microsoft/MixedRealityToolkit#192]
![default](https://user-images.githubusercontent.com/13955075/49576753-e05b2580-f980-11e8-9f9f-edc690c9cc93.png)
![default](https://user-images.githubusercontent.com/13955075/49577521-878c8c80-f982-11e8-977d-50dc4762a614.png)
I follow those steps and When i move to step "Set the build options to Release and x86, then build the solution" i get the error "opencv2/arcu.hpp : no such file or directory ", so I build failed.I dont know how to solve this problem,If someone help me  I will appreaciate it.
![default](https://user-images.githubusercontent.com/13955075/49577876-637d7b00-f983-11e8-9fac-939ee027cbfc.png)

**Comment by karloberas** [comment]
OpenCV may not be installed properly

**Comment by chrisfromwork** [comment]
@Emerson92 were you able to get past this issue?

**Comment by chrisfromwork** [comment]
I am closing this issue based on a lack of activity. Please reopen this issue if the problem persists.
