### ISSUE TITLE
vcpkg UWP build failed (Cmake)

### ISSUE THREAD

**Issue by cindychen0204** [microsoft/MixedRealityToolkit#195]
Failed to do post-extract rename-in-place.
fs.rename(C:\Users\cindy\git\vcpkg\downloads\tools\cmake-3.11.4-windows.partial.20804, C:\Users\cindy\git\vcpkg\downloads\tools\cmake-3.11.4-windows, operation not permitted)

this error I have never met before.
It seems like there is something wrong with git number : 068032bc548817a04709970f76268a6d7b1767c7.

btw, I build successfully in Dec 2018 in another PC, now it is showing I need some updates.

please update it or give any other solution.

Thank you.

**Comment by karloberas** [comment]
I got the same issue. Delete the folder in C:\Users\cindy\git\vcpkg\downloads\tools\cmake-3.11.4-windows. Install Cmake by yourself then run the command again worked for me.

**Comment by chrisfromwork** [comment]
Hello,

It seems like the documentation needs updated. At the time the vcpkg 068032bc548817a04709970f76268a6d7b1767c7 suggestion was committed to this repo, it was working for me locally. This morning I was able to move vcpkg to 05b31030cee412118a9710daf5b4652a684b7f50 for my local setup. Setup and install then succeeded for me.

**Comment by chrisfromwork** [comment]
@cindychen0204 were you able to get past this issue?

**Comment by chrisfromwork** [comment]
I believe vcpkg has fixed this issue. Although this issue blocks the spectator view experience, it isn't related to any spectator view specific code. Please reopen this issue against the microsoft/vcpkg repo in the future if problems persist.
