### ISSUE TITLE
Spectator View Unity build fails: 'Matrix4x4' does not exist in 'System.Numerics'

### ISSUE THREAD

**Issue by benjamincoven** [Microsoft/MixedRealityToolkit#206]
Hello,

I have a probleme building a Unity project with spectator view plugin for UWP target, I get the following errors:

![image](https://user-images.githubusercontent.com/12698212/52065065-1af2d000-2576-11e9-8911-7f0909b94b09.png)

I am using SDK 10.0.17763.0

Thank you

**Comment by chrisfromwork** [comment]
Hello,

Those types might exist in both the UnityEngine namespace and the System.Numerics namespace. What platform are you trying to build (Standalone, UWP, etc)? If you remove using System.Numerics from the SpatialGraphCoordinateSystem.cs file do these types resolve to the UnityEngine namespace? If you switch to building UWP do these types resolve correctly? It may be that the System.Numerics namespace is stubbed out behind a UNITY_WSA or WINDOWS_UWP macro, so the specific platform you are targetting does not resolve things correctly.

**Comment by chrisfromwork** [comment]
By the way, if you are trying to build the spectator view preview code, QRTracker is not needed. You can delete this directory in your local setup to get past this issue if you don't need QR Code detection (Spectator view preview marker detection is based on ArUco markers which aren't the same as qr codes).

**Comment by benjamincoven** [comment]
Removing QRTracker did the trick. Thank you very much.

I was targeting UWP, haven't investigated more since the build succeeded.
