### ISSUE TITLE
The SpectatorViewPlugin solution

### ISSUE THREAD

**Issue by eswarborra** [Microsoft/MixedRealityToolkit#216]
I am Unable to open this page.

![Screenshot 2019-04-08 at 5 51 51 PM](https://user-images.githubusercontent.com/23381032/55723614-1d1a5480-5a27-11e9-894d-99481e324ac2.png)
The SpectatorViewPlugin solution generates a dll needed for the SpectatorView experience in the MixedRealityToolkit-Unity repo: https://github.com/Microsoft/MixedRealityToolkit-Unity/tree/master/Assets/HoloToolkit-Preview/SpectatorView.

**Comment by keveleigh** [comment]
Fixed via #218. Thanks for the report!

**Comment by eswarborra** [comment]
but still not showing
