### ISSUE TITLE
MRTK assets having shaders issue (shaders being pink )

### ISSUE THREAD

**Issue by ashwinir05** [microsoft/MixedRealityToolkit#274]
NullReferenceException: Object reference not set to an instance of an object
Microsoft.MixedReality.Toolkit.UI.Interactable.ResolveInputAction (System.Int32 index) (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@f580191fa165-1618379598381/SDK/Features/UX/Interactable/Scripts/Interactable.cs:1161)
Microsoft.MixedReality.Toolkit.UI.Interactable.Initialize () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@f580191fa165-1618379598381/SDK/Features/UX/Interactable/Scripts/Interactable.cs:758)
Microsoft.MixedReality.Toolkit.UI.Interactable.EnsureInitialized () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@f580191fa165-1618379598381/SDK/Features/UX/Interactable/Scripts/Interactable.cs:743)
Microsoft.MixedReality.Toolkit.UI.Interactable.Awake () (at Library/PackageCache/com.microsoft.mixedreality.toolkit.foundation@f580191fa165-1618379598381/SDK/Features/UX/Interactable/Scripts/Interactable.cs:616)

**Comment by keveleigh** [comment]
Going to close based on the Unity repo issue: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9924
