### ISSUE TITLE
Queries about plane finding

### ISSUE THREAD

**Issue by AvinashNargund** [microsoft/MixedRealityToolkit#281]
Hi, I am using [PlaneFinding](https://github.com/microsoft/MixedRealityToolkit/tree/main/SpatialMapping/PlaneFinding/UnityAddon) to detect flat surfaces in my room. So I did a 3D scan of my room using the Hololens2 and use the generated `obj` file to test the plane finding algorithm. I have the following questions about this - 
1. The PlaneFinding API returns the detected planes in the form of an array of `BoundedPlane`. Is there an easy/recommended way to visualize these detected planes?
2. Since I couldn't find a way recommended way of visualizing the planes, I wrote up some code to generate GameObjects with `Plane` meshes and set their position and size using the `Center`, `Rotation` and `Extents` of the detected planes. But the results definitely look wrong (see screenshot below). Can someone please tell me what the issue could be? 
3. Would it be possible to modify the API so that it could potentially return the meshes associated with each plane? 
![planefinding](https://user-images.githubusercontent.com/16573247/166064932-8420a5a7-dcdb-4f55-a695-e2e1d76b4e26.png)

**Comment by keveleigh** [comment]
If you're looking for more info on the PlaneFinding plugin, [Holograms 230](https://docs.microsoft.com/windows/mixed-reality/develop/unity/tutorials/holograms-230) uses it pretty extensively. The content is likely out of date overall, but it should use PlaneFinding in a pretty comparable way.

Overall though, we're moving away from the PlaneFinding DLL in this plugin in favor of Scene Understanding:
1. https://docs.microsoft.com/windows/mixed-reality/develop/unity/scene-understanding-sdk
1. https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/features/spatial-awareness/scene-understanding?view=mrtkunity-2021-05

**Comment by AvinashNargund** [comment]
Alright, sounds good, thanks @keveleigh!
