### ISSUE TITLE
Deprecation/Removal of support for third-party devices?

### ISSUE THREAD

**Issue by hereBeDragons781** [microsoft/MixedRealityToolkit#311]
https://learn.microsoft.com/en-us/windows/whats-new/deprecated-features

**Comment by AMollis** [comment]
Unclear what this issue is here.  If this is a document bug, please open in the corresponding feedback link on the documentation page

<img width="326" alt="image" src="https://github.com/microsoft/MixedRealityToolkit/assets/36461279/603d4f47-91e7-4216-ba5f-d602dc723358">
