### ISSUE TITLE
MicStreamSelector: Buffer NaNs

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MixedRealityToolkit#75]
Mic Stream Buffer values occasionally return NaNs & is not clamped between [-1,1] properly.
Ref https://github.com/Microsoft/HoloToolkit-Unity/issues/556

**Comment by davidkline-ms** [comment]
Found that the MicStreamDemo.cs file (in the Unity example project), checks for NaN and clamps the data.  The plugin is a simple copy.

Investigating the best place to perform the checks.

**Comment by StephenHodgson** [comment]
I was the one that added the NaN check.

**Comment by davidkline-ms** [comment]
Got it. Thanks, Stephen.
